random_quiz = ['CountRandomNumbers',
               'Dice',
               'Dice2',
               'Machigai5b',
               'MonteCarlo',
               'Omikuji',
               'RandomArray',
               'Ransu',
               'Ransu1',
               'Ransu2',
               'RansuRange',
               'Shuffle',
               'Sqrt']

double_quiz = ['Bmi',
               'Diagonal',
               'EnsuiTaiseki',
               'Floor1',
               'Graph14',
               'Heikin3',
               'Heikin4',
               'Heikin6',
               'Hoyuritu',
               'IntagerDecimal',
               'KyuTaiseki',
               'Machigai8',
               'MatVariance',
               'MensekiTaiseki',
               'PowerOfTwo',
               'RainFall',
               'Round1',
               'Tax10',
               'Var2',
               'Var4']