random_quiz = ['CountRandomNumbers.java',
               'Dice.java',
               'Dice2.java',
               'Machigai5b.java',
               'MonteCarlo.java',
               'Omikuji.java',
               'RandomArray.java',
               'Ransu.java',
               'Ransu1.java',
               'Ransu2.java',
               'RansuRange.java',
               'Shuffle.java',
               'Sqrt.java']

double_quiz = ['Bmi.java',
               'Diagonal.java',
               'EnsuiTaiseki.java',
               'Floor1.java',
               'Graph14.java',
               'Heikin3.java',
               'Heikin4.java',
               'Heikin6.java',
               'Hoyuritu.java',
               'IntagerDecimal.java',
               'KyuTaiseki.java',
               'Machigai8.java',
               'MatVariance.java',
               'MensekiTaiseki.java',
               'PowerOfTwo.java',
               'RainFall.java',
               'Round1.java',
               'Tax10.java',
               'Var2.java',
               'Var4.java']